---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: upbound-function-rds-metrics
spec:
  package: xpkg.upbound.io/upbound/function-rds-metrics:v0.0.3
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-claude
  annotations:
    render.crossplane.io/runtime: Development
spec:
  package: function-claude
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-auto-ready
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.2.1
